import express from 'express';
import { adminOnly, protect } from '../middleware/authMiddleware.js';
import { requirePermission } from '../middleware/permissionMiddleware.js';
import { PERMISSIONS } from '../constants/permissions.js';
import { answerBrowserCall, answerClickToCall, buyNumber, finalizeBrowserCall, getCallLogDetails, getTelephonyConfig, hangupClickToCall, listCallLogs, recordingCallback, retryCallTranscription, searchNumbers, selectNumber, transcriptionCallback, updateActiveCallingPool } from '../controllers/telephonyController.js';

const router = express.Router();
router.post('/webhooks/answer/:callLogId/:token', answerClickToCall);
router.post('/webhooks/hangup/:callLogId/:token', hangupClickToCall);
router.post('/webhooks/browser-answer', answerBrowserCall);
router.post('/webhooks/recording/:callLogId/:token', recordingCallback);
router.post('/webhooks/transcription/:callLogId/:token', transcriptionCallback);
router.get('/calls', protect, requirePermission(PERMISSIONS.CALLS_VIEW), listCallLogs);
router.get('/calls/:callLogId', protect, requirePermission(PERMISSIONS.CALLS_VIEW), getCallLogDetails);
router.post('/calls/:callLogId/transcription/retry', protect, requirePermission(PERMISSIONS.CALLS_MANAGE), retryCallTranscription);
router.post('/calls/:callLogId/finalize', protect, requirePermission(PERMISSIONS.CALLS_MANAGE), finalizeBrowserCall);
router.get('/numbers', protect, requirePermission(PERMISSIONS.CALLS_MANAGE), getTelephonyConfig);
router.get('/numbers/search', protect, adminOnly, searchNumbers);
router.post('/numbers/buy', protect, adminOnly, buyNumber);
router.put('/numbers/default', protect, adminOnly, selectNumber);
router.put('/numbers/active-pool', protect, adminOnly, updateActiveCallingPool);
export default router;
